CREATE TABLE IF NOT EXISTS movies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  year NUMERIC,
  theater_id INTEGER,
  created_at DATE DEFAULT (DATETIME('NOW')),
  updated_at DATE DEFAULT (DATETIME('NOW')),
  FOREIGN KEY(theater_id) REFERENCES theaters(id) ON DELETE CASCADE ON UPDATE CASCADE
);
