CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  body TEXT,
  blog_id INTEGER,
  created_at DATE DEFAULT (DATETIME('NOW')),
  updated_at DATE DEFAULT (DATETIME('NOW')),
  FOREIGN KEY(blog_id) REFERENCES blogs(id) ON DELETE CASCADE ON UPDATE CASCADE
);
